apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-ttl
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: composition-ttl
    functionRef:
      name: function-ttl
